# .github/workflows/ci.yml

name: CI

on:
  # push:
  #   branches: [main]
  # NOTE: The 'push' trigger above is commented out to prevent this CI workflow
  # from running a second time. The 'release.yml' workflow already calls this
  # workflow on pushes to main, making this trigger redundant.
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          node-version: lts/*

      - name: Lint
        run: nr lint

      - name: Typecheck
        run: nr typecheck

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          node-version: ${{ matrix.node }}

      - name: Test
        run: nr test
